### PR TITLE
Navigator now has history

### PR DESCRIPTION
**Pull request by sscaff1**
I think every navigator should manage history no matter how simple the API is. I added a goBack method and a resetHistory method. The state has also been updated to have a history key which contains the history. I updated the README to reflect these additions. Hope this falls in line with smalldots purpose.

### CODE REVIEW

**Review by hnordt — COMMENTED** [review]
Thank you, that's a great idea.

I would like to propose some changes so we'll have an API like https://developer.mozilla.org/en-US/docs/Web/API/History_API:
1. Rename gBack() to back()
2. Add forward()
3. Add getHistory()
4. Add go() (go(-1), go(2), etc)
5. Rename resetHistory() to reset()

**Comment by hnordt** [comment]
Ignore the last item, keep `resetHistory()`.

**Comment by sscaff1** [comment]
@hnordt nice suggestions. I can add these this week.

**Comment by sscaff1** [comment]
@hnordt I updated the PR

**Comment by hnordt** [comment]
Thank you @sscaff1, I hadn't time to review it yet, but I'll take a look as soon as possible.

At the moment I'm working on new components, like `EnhancedForm` and `Grid`.

**Comment by sscaff1** [comment]
@hnordt I realized I made a mistake because I need to include current index on setScene. I will clean that up tonight and also make sure the conflicts are resolved.

**Comment by hnordt** [comment]
Ok, thank you @sscaff1

**Comment by hnordt** [comment]
@sscaff1 I have added history support using https://github.com/mjackson/history.

New methods:
- getHistory()
- canGo(n)
- go(n)
- back()
- forward()

reset() isn't available yet.

**Pull request closed without merging**
